/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* src = "fin/d_logic.v:1" *)
module \$paramod\ands\N=2 (a, b, y);
  (* src = "fin/d_logic.v:2" *)
  input [1:0] a;
  (* src = "fin/d_logic.v:3" *)
  input [1:0] b;
  (* src = "fin/d_logic.v:4" *)
  output [1:0] y;
  assign y[0] = a[0] &(* src = "fin/d_logic.v:8" *)  b[0];
  assign y[1] = a[1] &(* src = "fin/d_logic.v:8" *)  b[1];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "fin/d_array_muls.v:1" *)
module array_mul(clk, inp, a, b, y);
  (* src = "fin/d_array_muls.v:4" *)
  input [1:0] a;
  (* src = "fin/d_array_muls.v:5" *)
  input [1:0] b;
  (* src = "fin/d_array_muls.v:2" *)
  input clk;
  (* src = "fin/d_array_muls.v:14" *)
  wire [1:0] ct;
  (* src = "fin/d_array_muls.v:12" *)
  wire [3:0] from_reg;
  (* src = "fin/d_array_muls.v:3" *)
  input inp;
  (* src = "fin/d_array_muls.v:1" *)
  (* unused_bits = "0 1" *)
  wire [3:0] \pp1[0] ;
  (* src = "fin/d_array_muls.v:1" *)
  (* unused_bits = "1 2" *)
  wire [3:0] \pp1[1] ;
  (* src = "fin/d_array_muls.v:1" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \pp[0] ;
  (* src = "fin/d_array_muls.v:1" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \pp[1] ;
  (* src = "fin/d_array_muls.v:6" *)
  inout [3:0] y;
  assign ct = 2'h0;
  assign from_reg = 4'h0;
  assign \pp1[0] [3:2] = 2'h0;
  assign { \pp1[1] [3], \pp1[1] [0] } = 2'h0;
  assign \pp[0]  = \pp1[0] [1:0];
  assign \pp[1]  = \pp1[1] [2:1];
  assign y = 4'h0;
endmodule
